### ISSUE TITLE
i know you're location

### ISSUE THREAD

**Issue by MemeFlavor** [NimuFurrySoftUwU/FNF-VS-JEFFERSON13N#35]
### Describe your bug here.

you cant run away from me

```geojson
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -531.5625,
              -84.92832092949963
            ],
            [
              -164.53125,
              -84.92832092949963
            ],
            [
              -164.53125,
              85.1709701284095
            ],
            [
              -531.5625,
              85.1709701284095
            ],
            [
              -531.5625,
              -84.92832092949963
            ]
          ]
        ]
      }
    }
  ]
}
```

### Command Prompt/Terminal logs (if existing)

```bash
run
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

run run run

**Comment by lolbruhfart** [comment]
WTF HOW DID YOU GET MY LOCATION TOO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by MemeFlavor** [comment]
run before i get you

**Comment by ManMaster707** [comment]
YOU [WHAT](https://www.youtube.com/watch?v=dwFfD7ouvKM)?!?!

**Comment by MemeFlavor** [comment]
> YOU [WHAT](https://www.youtube.com/watch?v=dwFfD7ouvKM)?!?!

[are you in there?](https://github.com/NimuFurrySoftUwU/FNF-VS-JEFFERSON13N/files/9168830/are.you.in.there.mp3.zip)
